Repository CodersCamp2020-HK/CodersCamp2020.Project.FullStack-Node-React, pull requests merged in 2021-04, with the labels that each got.

#224 New colors and background
  src/presentation/web/public/favicon.ico
  src/presentation/web/public/index.html
  src/presentation/web/src/assets/lapki.svg
  src/presentation/web/src/components/logo/Logo.tsx
  src/presentation/web/src/components/logo/logo.svg
  src/presentation/web/src/components/navbar/Navbar.tsx
  src/presentation/web/src/themes/theme.tsx
Labels: Development Task

#219 Get organization users
  src/IocContainerSetup.ts
  src/application/OrganizationUsersService.ts
  src/presentation/rest/OrganizationUsersController.ts
Labels: Development Task

#230 Landing hero
  src/presentation/web/src/App.tsx
  src/presentation/web/src/components/animationPaws/AnimationPaws.tsx
  src/presentation/web/src/components/animationPaws/img/PawIcon.tsx
  src/presentation/web/src/components/landingHero/LandingHero.tsx
  src/presentation/web/src/components/landingHero/img/Landing-hero.jpg
  src/presentation/web/src/components/page404/Page404.tsx
  src/presentation/web/src/pages/Home.tsx
Labels: Development Task

#217 Gallery
  src/application/AnimalsService.ts
  src/infrastructure/postgres/dummyData/animalPhoto.ts
  src/infrastructure/postgres/dummyData/dog.png
  src/infrastructure/postgres/seedDatabase.ts
  src/presentation/web/.env
  src/presentation/web/.env.development
  src/presentation/web/package-lock.json
  src/presentation/web/package.json
  src/presentation/web/src/App.tsx
  src/presentation/web/src/components/animalCard/AnimalCard.tsx
  src/presentation/web/src/components/animationPaws/AnimationPaws.tsx
  src/presentation/web/src/components/animationPaws/img/PawIcon.tsx
  src/presentation/web/src/components/contactPage/ContactPage.tsx
  src/presentation/web/src/components/filterPanel/FilterPanel.tsx
  src/presentation/web/src/components/filterPanel/LocalTheme.tsx
  src/presentation/web/src/components/gallery/Gallery.tsx
  src/presentation/web/src/components/gallery/dog.png
  src/presentation/web/src/components/galleryPage/GalleryPage.tsx
  src/presentation/web/src/components/gridContainer/GridContainer.tsx
  src/presentation/web/src/components/landingHero/LandingHero.tsx
  src/presentation/web/src/components/page404/Page404.tsx
  src/presentation/web/src/components/page404/img/PawIcon404.tsx
  src/presentation/web/src/pages/Home.tsx
Labels: Development Task

#227 Generic dialog
  src/presentation/web/package.json
  src/presentation/web/src/components/genericDialog/Dialog.test.tsx
  src/presentation/web/src/components/genericDialog/Dialog.tsx
  src/presentation/web/src/testUtils/muiWrapper.tsx
Labels: Development Task

#231 Animal info card
  src/application/AnimalSubmissionsService.ts
  src/application/AnimalsService.ts
  src/application/UsersService.ts
  src/application/VolunteerSubmissionsService.ts
  src/presentation/web/src/App.tsx
  src/presentation/web/src/components/animalInfoCard/AnimalInfoCard.test.tsx
  src/presentation/web/src/components/animalInfoCard/AnimalInfoCard.tsx
  src/presentation/web/src/components/animalInfoDescription/AnimalInfoDescription.test.tsx
  src/presentation/web/src/components/animalInfoDescription/AnimalInfoDescription.tsx
  src/presentation/web/src/components/slider/Slider.tsx
  src/presentation/web/src/pages/AnimalInfo.tsx
  src/presentation/web/src/testUtils/muiWrapper.tsx
  src/presentation/web/src/utils/formatText/formatActiveLevel.ts
  src/presentation/web/src/utils/formatText/formatDate.ts
  src/presentation/web/src/utils/formatText/formatSize.ts
Labels: Development Task

#245 visual fix to component
  src/presentation/web/src/components/landingHero/LandingHero.tsx
Labels: Development Task

#248 Get animal photos
  src/application/AnimalsService.ts
  src/presentation/rest/AnimalsController.ts
  src/presentation/web/src/pages/AnimalInfo.tsx
Labels: Development Task

#253 Strona adopcja-> Proces adopcyjny
  src/presentation/web/src/components/pageAdopt/PageAdopt.tsx
  src/presentation/web/src/components/pageAdopt/adoptionStepCard/AdoptionStepCard.tsx
  src/presentation/web/src/components/pageAdopt/adoptionStepCard/AdoptionSteps.tsx
  src/presentation/web/src/pages/Adoption.tsx
Labels: Development Task

#242 app contex
  src/presentation/web/package-lock.json
  src/presentation/web/package.json
  src/presentation/web/src/App.tsx
  src/presentation/web/src/components/auth/loginForm/LoginForm.tsx
Labels: Development Task

#243 My acc btn
  src/presentation/web/src/components/myAccBtn/MyAccBtn.tsx
  src/presentation/web/src/components/navbar/Navbar.tsx
Labels: Development Task

#247 Calendar
  src/presentation/web/src/components/calendar/Calendar.tsx
  src/presentation/web/src/components/timePicker/TimePicker.tsx
  src/presentation/web/src/components/visitForm/VisitForm.tsx
Labels: Development Task

#257 add key prop and style fix
  src/presentation/web/src/App.tsx
  src/presentation/web/src/components/pageAdopt/PageAdopt.tsx
  src/presentation/web/src/components/pageAdopt/adoptionStepCard/AdoptionStepCard.tsx
  src/presentation/web/src/components/pageAdopt/adoptionStepCard/AdoptionSteps.tsx
Labels: Bug, Development Task

#226 Adoption application first step
  src/presentation/web/src/App.tsx
  src/presentation/web/src/components/adoptionApplicationFirstStep/AdoptionApplicationFirstStep.tsx
  src/presentation/web/src/pages/Adoption.tsx
Labels: Development Task

#259 redirect from AnimalCard to AnimalInfo
  src/presentation/web/src/App.tsx
  src/presentation/web/src/components/animalCard/AnimalCard.tsx
  src/presentation/web/src/components/galleryPage/GalleryPage.tsx
Labels: Development Task

#264 Confirmed visit date
  src/presentation/web/src/components/confirmedVisitDate/ConfirmedVisitDate.tsx
Labels: Development Task

#277 ProtectedRoute
  src/presentation/web/src/App.tsx
  src/presentation/web/src/components/contactPage/ContactPage.tsx
  src/presentation/web/src/components/gridContainer/GridContainer.tsx
  src/presentation/web/src/components/navbar/navbar/Navbar.tsx
  src/presentation/web/src/components/protectedRoute/ProtectedRoute.tsx
  src/presentation/web/src/components/sideNav/SideNavList.tsx
  src/presentation/web/src/pages/Adoption.tsx
  src/presentation/web/src/pages/AnimalInfo.tsx
  src/presentation/web/src/pages/Auth.tsx
  src/presentation/web/src/pages/FormRoute.tsx
  src/presentation/web/src/pages/MyAcc.tsx
  src/presentation/web/src/pages/NotFound.tsx
Labels: Development Task

#280 Google maps fix
  src/infrastructure/express/SecurityMiddleware.ts
Labels: Development Task

#283 Stepper
  src/presentation/web/src/components/stepper/AdoptionStepper.tsx
Labels: Development Task

#281 Visit confirmed
  src/presentation/web/src/components/calendar/Calendar.tsx
  src/presentation/web/src/components/visitConfirmed/VisitConfirmed.tsx
Labels: Development Task

#285 SideNav routing
  src/infrastructure/postgres/dummyData/organizationUsers.ts
  src/infrastructure/postgres/dummyData/users.ts
  src/presentation/web/.env
  src/presentation/web/src/App.tsx
  src/presentation/web/src/components/auth/loginForm/LoginForm.tsx
  src/presentation/web/src/components/navbar/navbar/Navbar.tsx
  src/presentation/web/src/components/sideNav/SideNavList.tsx
  src/presentation/web/src/pages/Animals.tsx
  src/presentation/web/src/pages/Applications.tsx
  src/presentation/web/src/pages/Auth.tsx
  src/presentation/web/src/pages/Calendar.tsx
  src/presentation/web/src/pages/Logout.tsx
  src/presentation/web/src/pages/MyAcc.tsx
  src/presentation/web/src/pages/Profile.tsx
  src/presentation/web/src/pages/Users.tsx
  src/presentation/web/src/pages/Volunteer.tsx
  src/presentation/web/src/pages/Volunteers.tsx
Labels: Development Task

#290 Mobile NavSide
  src/presentation/web/src/components/navbar/sideNav/SideNav.tsx
  src/presentation/web/src/pages/Animals.tsx
  src/presentation/web/src/pages/MyAcc.tsx
  src/presentation/web/src/themes/theme.tsx
Labels: Development Task

#284 Add photo input
  src/application/AnimalsService.ts
  src/presentation/rest/AnimalsController.ts
  src/presentation/web/src/components/addPhotoInput/AddPhotoInput.tsx
  src/presentation/web/src/components/addPhotoInput/fileUploadExample.txt
Labels: Development Task

#301 Loading animation
  src/presentation/web/src/components/animalInfoCard/AnimalInfoCard.tsx
  src/presentation/web/src/components/animalInfoDescription/AnimalInfoDescription.tsx
  src/presentation/web/src/components/auth/changePassword/ChangePassword.tsx
  src/presentation/web/src/components/auth/forgetPassword/ForgetPassword.tsx
  src/presentation/web/src/components/auth/loginForm/LoginForm.tsx
  src/presentation/web/src/components/firstStep/FirstStep.tsx
  src/presentation/web/src/components/forms/registerForm/RegisterForm.tsx
  src/presentation/web/src/components/forms/surveyForm/SurveyForm.tsx
  src/presentation/web/src/components/forms/visitForm/VisitForm.tsx
  src/presentation/web/src/components/gallery/Gallery.tsx
  src/presentation/web/src/components/loadingCircle/LoadingCircle.tsx
  src/presentation/web/src/components/loadingCircleSmall/LoadingCircleSmall.tsx
  src/presentation/web/src/pages/AnimalInfo.tsx
Labels: Development Task

#303 Uncomment email code
  src/infrastructure/EmailService.ts
Labels: Development Task

#298 Adoption sign agreement
  src/presentation/web/src/components/common/stepper/AdoptionStepper.tsx
  src/presentation/web/src/components/invitationForSignAgreement/Invitation.tsx
  src/presentation/web/src/pages/About.tsx
  src/presentation/web/src/pages/Adoption.tsx
  src/presentation/web/src/pages/InvitationSuccessAdoption.tsx
  src/presentation/web/src/pages/MyAcc.tsx
Labels: Development Task

#287 Application adoption processing
  src/presentation/web/src/components/formsProcessing/FormAdoptionChooseDate.tsx
  src/presentation/web/src/components/formsProcessing/FormVolounteerDate.tsx
  src/presentation/web/src/components/formsProcessing/formProcessing.tsx
Labels: Development Task

#307 Animals filter
  src/presentation/web/src/components/aboutUs/aboutUs.tsx
  src/presentation/web/src/components/animalCard/AnimalCard.tsx
  src/presentation/web/src/components/contactPage/ContactPage.tsx
  src/presentation/web/src/components/filterPanel/LocalTheme.tsx
  src/presentation/web/src/components/gallery/Gallery.tsx
  src/presentation/web/src/components/galleryPage/GalleryPage.tsx
  src/presentation/web/src/components/gridContainer/GridContainer.tsx
  src/presentation/web/src/pages/Adoption.tsx
  src/presentation/web/src/pages/AnimalInfo.tsx
  src/presentation/web/src/pages/Animals.tsx
  src/presentation/web/src/pages/Auth.tsx
  src/presentation/web/src/pages/Home.tsx
  src/presentation/web/src/pages/MyAcc.tsx
Labels: Development Task

#313 Optional filter
  src/presentation/web/src/components/gallery/Gallery.tsx
  src/presentation/web/src/components/galleryPage/GalleryPage.tsx
  src/presentation/web/src/components/notFoundResults/NotFoundResults.tsx
  src/presentation/web/src/pages/Animals.tsx
Labels: Development Task

#305 End Adoption Process
  src/presentation/rest/UsersController.ts
  src/presentation/web/src/App.tsx
  src/presentation/web/src/components/endAdoptionProcess/EndAdoptionProcess.tsx
  src/presentation/web/src/components/visitConfirmed/VisitConfirmed.tsx
Labels: Development Task

#314 Waiting for confirmation
  src/presentation/web/src/components/waitingForVisitConfirmation/WaitingForVisitConfirmation.tsx
Labels: Development Task

#316 Page in progress
  src/presentation/web/src/App.tsx
  src/presentation/web/src/assets/under-construction.jpg
  src/presentation/web/src/pages/Donation.tsx
  src/presentation/web/src/pages/PageInProgress.tsx
Labels: Development Task

#324 add foto
  src/infrastructure/postgres/dummyData/animalPhoto.ts
  src/infrastructure/postgres/dummyData/cat1.png
  src/infrastructure/postgres/dummyData/cat2.png
  src/infrastructure/postgres/dummyData/cat3.png
  src/infrastructure/postgres/dummyData/cat4.png
  src/infrastructure/postgres/dummyData/cat5.png
  src/infrastructure/postgres/dummyData/catt1.png
  src/infrastructure/postgres/dummyData/catt2.png
  src/infrastructure/postgres/dummyData/catt3.png
  src/infrastructure/postgres/dummyData/catt4.png
  src/infrastructure/postgres/dummyData/catt5.png
  src/infrastructure/postgres/dummyData/dog1.png
  src/infrastructure/postgres/dummyData/dog2.png
  src/infrastructure/postgres/dummyData/dog3.png
  src/infrastructure/postgres/dummyData/dog4.png
  src/infrastructure/postgres/dummyData/dog5.png
  src/infrastructure/postgres/dummyData/dogg1.png
  src/infrastructure/postgres/dummyData/dogg2.png
  src/infrastructure/postgres/dummyData/dogg3.png
  src/infrastructure/postgres/dummyData/dogg4.png
  src/infrastructure/postgres/dummyData/dogg5.png
  src/infrastructure/postgres/seedDatabase.ts
  src/presentation/web/src/components/slider/Slider.tsx
Labels: Development Task

#322 Animal not found i drobne fixy
  src/presentation/web/src/components/animalInfoCard/AnimalInfoCard.test.tsx
  src/presentation/web/src/components/animalInfoCard/AnimalInfoCard.tsx
  src/presentation/web/src/components/pageAdopt/adoptionStepCard/AdoptionSteps.tsx
  src/presentation/web/src/pages/AnimalInfo.tsx
Labels: Development Task

#318 Update README.md
  README.md
Labels: Dokumentacja
